# .streamlit/secrets.toml
[connections.neon]
url = "postgresql://neondb_owner:npg_Zf2b3FjPdnvh@ep-frosty-fog-at6gioza-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
